### ISSUE TITLE
Separating slicing from plotting

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-heatmaps#3]
I'm checking out the API of the package, and I see that at the moment a single class `heatmap` (I'd suggest renaming to `Heatmap`) is taking care of both the slicing and the plotting. In this way there's no easy way for the user to just use the package to get a plottable slice, and not use the default matplotlib visualisation.

I would suggest conceptually splitting the slicing from the plotting. Maybe there could be a `Slicer` class, that performs what now is in `self.slice()` and can be used to just return the coordinates to be plot, and a `Heatmap` class with the features of the current one?

**Comment by vigji** [comment]
awesome! No, would no really see now an application for that.

If I can just suggest a naming change, `bgh.get_plane_coordinates` feels like you're getting the coordinates that define the plane. Maybe Something along the lines of `get_slice_coordinates` or `slice_structures` or `get_structures_slice_coords`?

**Comment by FedeClaudi** [comment]
Fair, done
