### ISSUE TITLE
Testing out the examples

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-heatmaps#4]
I'm testing out the heat map 2D example and out of the box after installation I get this:
<img width="556" alt="Screenshot 2022-01-21 at 14 19 54" src="https://user-images.githubusercontent.com/10400212/150533805-2dcd2aa0-c00c-4cf2-8e73-4f032ed094be.png">

It feels like the sorting fails for a portion of the root mask, is this something that happens for you as well?

**Comment by FedeClaudi** [comment]
The plane needs to be big enough such that it slices the entire mesh. I thought I had fixed it but it was still a bit too small, now it's okay:

![image](https://user-images.githubusercontent.com/17436313/150535048-9c92ce05-eb7b-4f5a-9843-de15250323e0.png)
