### ISSUE TITLE
Can not install bgheatmaps

### ISSUE THREAD

**Issue by chaoshengt** [brainglobe/bg-heatmaps#6]
Dear @FedeClaudi , I can not install bgheatmaps  via  pip install bgheatmaps. 
```python
ERROR: Could not find a version that satisfies the requirement bgheatmaps (from versions: none)                                                                      
ERROR: No matching distribution found for bgheatmaps   
```

**Comment by vigji** [comment]
Dear @chaoshengt, you seem to have a typo. The right installation is

`pip install bgheatmap`

**Comment by adamltyson** [comment]
To be fair, the typo is in the readme @FedeClaudi

**Comment by FedeClaudi** [comment]
My bad! Typos fixed now, `pip install bgheatmap` should work.

**Comment by chaoshengt** [comment]
> 



> My bad! Typos fixed now, `pip install bgheatmap` should work.

It is done, Thank you! :)
